### ISSUE TITLE
老哥，现在状态如何？

### ISSUE THREAD

**Issue by woniuxia** [i0Ek3/work-and-life-in-system#12]
RT，一定有一些想分享的吧

**Comment by i0Ek3** [comment]
是有很多要分享，不过这里只能简单聊一下，后面有机会我再单独整理吧。甚至我还写了一篇文字专门给应届生或者从未在互联网工作过而又想来工作的人作为入门，但还没有发出来，后面我再整理一下。

总之，我现在的状态就是顺其自然，在这边更大的感受就是及时沟通。

前期的时候感觉人容易崩，很多东西都无从下手，又不好意思问人，只能自己花时间，导致被 leader 沟通说我的方向不对。毕竟很多时候事项是很紧急的，所以自己“闷声发大财”是不可行的。到现在，自己也能了解个大概，但依然感觉进度很慢，很多思维方式还转变不过来，但也在努力适应（如果实在适应不过来我也不会继续 push 自己了，应该及时止损）。最主要的是我这边很卷，我已经有很多次晚上11点之后下班了，这点让我有点 hold 不住。另外，我也发现自己写代码和在公司写代码完全是两码事，感受非常地不一样，甚至我有点适应不了公司的这种形式。

所以，后面无论是过了试用期继续留用还是在试用期内被裁员又或者以不符合预期被干掉，对我来说都不如身体和心理健康重要。就走一步看一步吧，毕竟很多事情无法预料。

到现在，想要的大厂感受、高强度工作体验以及在体制内的感受也都算是真真切切的体受过了，剩下的就是锚定自己的方向持续沉淀输出了。至于锚定何种方向或者何种人生，就需要我深度思考那些个究极问题了。

略长，共勉。

**Comment by woniuxia** [comment]
老哥，可以多和同事交流接触，特别是 mentor。
你要趁着你刚进入的这段时间多请教多问，因为刚开始你不懂不会是情有可原的，等时间久了，你还不会不知道，人家会觉得你不尽职，学习能力不足，接受能差。
在私企，你更需要积极主动，有一些似是而非的问题，你需要问清楚，在互联网公司时间真的显的特别紧，时间节点很重要。
关于加班这点，老哥之前没有做思想预期吗？十点多上班的互联网公司加班到晚上十点左右是常态，偶尔十一点是正常的，但是真要计算起来工作时间也是八个小时的。
我之前在互联网大厂工作了四年，有相关问题欢迎一起讨论。

关于未来，老哥有哪些可能的想法？
最近，在尝试自我催眠，人生哪有那么多有意义的事情，找一份安稳的工作，寻找生活中的乐趣也挺好。
可也总是左顾右盼，思来想去，怕这怕那的。
虽然不管怎么样都是会后悔的。
人生呀~

**Comment by i0Ek3** [comment]
非常感谢你的建议，怕是我很难打通了。不愿主动沟通这个，一是性格使然，二是自卑导致。至于跟不上脚步，要么方法不对要么不够聪明。所以，无论从哪点来讲，在这都是比较要命的。至于加班我是能想到的，只不过太晚我很难通过休息来弥补了，就是整个人的状态都不好了。至于你说的，我现在才能体会找一份稳定工作其实胜过那些虚荣的感受，一定要认清自己是普通人。想了一下，我所有的不好感受其实都来自自卑和虚荣，追求了错误的东西。至于之后的决定，其实我也在纠结。我现在也在试探自己的边界，不过我大概确定了我的边界在哪以及我真正感兴趣的事情。后面我大概率会自己做一些事情或者加入一些公益组织，做一些服务型的事业。其次也会继续提升英语水平，可以走出去看看。不过这都是理想化的，实际上我也只能照着计划走一步看一步，及时调整反馈。到现在才明白，能够承认自己不行（或者不足）才是真正的成长。至于选啥都会有顾虑，不如就选自己真心喜欢的东西，这个应该不会错。我算是两次都踏入了同一条河流，真是悲伤逆流成河啊！反正有些路自己不走永远领悟不到，多走的弯路也不是只有不好的方面，这样安慰自己就说的过去了。不过你现在在做什么呢？有什么可以分享的吗？或许可以加wc/tg分享下🤔

**Comment by woniuxia** [comment]
wx:yumenawei
老哥可以加下

**Comment by woniuxia** [comment]
- 承认自己是个普通人
- 人们常常被名利所捆绑，要想办法跳出去
- 以终为始，终是什么，是个致命的问题
- 人生漫漫，走一步欣赏一步，谁也不知道怎么走
- 失败了，也是经历，人生贵在体验
和老哥有太多相同的想法和思考。

**Comment by i0Ek3** [comment]
已加

**Comment by woniuxia** [comment]
没收到，重新加下，或者你发出来，我加你
