### ISSUE TITLE
请教下博主最近的状态如何

### ISSUE THREAD

**Issue by ritajie** [i0Ek3/work-and-life-in-system#14]
我看到您开了个雅思相关的 repo，难道是准备离开体制、出国学习工作了？😦

**Comment by i0Ek3** [comment]
> 我看到您开了个雅思相关的 repo，难道是准备离开体制、出国学习工作了？😦

是的。在体制里极度摆烂，大部分时间用于雅思复习，然后离开。

**Comment by ritajie** [comment]
感谢回复！抱歉我才发现有一篇 [Bye.md](https://github.com/i0Ek3/work-and-life-in-system/blob/master/Bye.md)。祝您前途似锦！

我正在憧憬体制内的工作，还想请教楼主一个问题：**程序员既然对计算机很熟悉，那么体制内的大多数工作（处理表格、写文章之类），是不是非常容易？** 比如随手写个脚本批量处理数据、用 AI 生成文章草稿等。

**Comment by i0Ek3** [comment]
> 感谢回复！抱歉我才发现有一篇 [Bye.md](https://github.com/i0Ek3/work-and-life-in-system/blob/master/Bye.md)。祝您前途似锦！
> 
> 我正在憧憬体制内的工作，还想请教楼主一个问题：**程序员既然对计算机很熟悉，那么体制内的大多数工作（处理表格、写文章之类），是不是非常容易？** 比如随手写个脚本批量处理数据、用 AI 生成文章草稿等。

其实这个仓库是2年前完成的，也就意味着2年前我就已经离开体制了。虽然我现在又回来了，不过这次只是暂留。

对于在体制内的工作本身来讲，其实并不复杂，复杂的是处理人际关系以及如何划分界限，这才是让人痛苦的地方。

当然，体制内的工作确实很多都是做表和写公文，通过脚本或者 AI 可以解决大部分问题。AI 写的公文不一定符合内部要求，笔杆子好的人可能会细究。不过到头来会发现，做啥其实都没有意义，不如想着如何躺平提升自己（个人拙见哈）。

一点建议：如果真要选择体制，前期最好想办法好好打探下单位的量级以及做计算机这块的情况，有没有自建项目或者系统啥的。可以去你想去的单位的官网查看相关科室，给他们打电话询问。如果在当地，直接上门拜访，我觉着也是没问题的。不然，一定会有时间让你后悔的。最好结合我国的发展蓝图（十四五规划）先确定那些比较 fancy 的行业，然后再来选你想要去的单位。

做好心理准备呦：庙小妖风大，水浅王八多。祝好哈，有问题随时问我~

**Comment by ritajie** [comment]
超级感谢您的建议！
