### ISSUE TITLE
看完了，我选择继续互联网加班

### ISSUE THREAD

**Issue by coderzhw** [i0Ek3/work-and-life-in-system#7]
看完了，还是不去想铁饭碗了，继续加班。

**Comment by i0Ek3** [comment]
哈哈，坚信自己所坚持的。

**Comment by coderzhw** [comment]
> 哈哈，坚信自己所坚持的。

一直在看你的追更，咱两性格比较像，哈哈，你没考虑过继续回互联网吗？我目前跟你的情况有些相似，在一个人人羡慕的大国企，技术做的不开心，没价值，没意义，和你们单位太像了

**Comment by i0Ek3** [comment]
哈哈，有句话怎么讲来着？幸福的家庭千篇一律，不幸的家庭各有不同。我不确定这句话对不对，但是你肯定已经知道了答案。欢迎收看我新更新的故事，祝好呀！
