### ISSUE TITLE
读完了，感谢分享，似乎也没那么坏

### ISSUE THREAD

**Issue by SaulJWu** [i0Ek3/work-and-life-in-system#9]
毕竟在哪里都会有这样的人，私企就没了吗，一样有。

**Comment by i0Ek3** [comment]
其实在哪里都一样，需要与自己和解，根据个人特点，再去做出权衡。

**Comment by coderzhw** [comment]
> 毕竟在哪里都会有这样的人，私企就没了吗，一样有。

私企可以想走就走，事业单位可以吗？走得了吗？出来能找到工作吗？
